### ISSUE TITLE
Browser plugin doesn't respond with list

### ISSUE THREAD

**Issue by jknight** [pyrho/alfred-firefoxtabswitch#2]
1. I followed the install steps (thanks for those!)
2. I have the extension installed in FF v77.01 (macos)
3. When I do Alfred -> fw the tab switcher comes up. 
4. If I run app.js via `node app.js` in "interactive mode (~/.noden/v/10.2/l/n/alfred-firefoxtabswitch/host) I can see the request coming in (Note: maybe my node version needs to be newer ? v10.20.1)
    
    > Sending to extension : {"cmd":"getTabList","requestId":15}
    >     #{"cmd":"getTabList","requestId":15}> got message from client: getTabList

5. **But FF isn't responding with a list of tabs**
6. I uncommented the logging in utils.js logToFile so I can get debug info

Any suggestions for troubleshooting the browser plugin / native manifest piece?

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/84268/84791193-35521000-afea-11ea-8581-80585da08fc9.png">

**Comment by pyrho** [comment]
Hey,

Running `node app.js` won't help, this need to be launched by firefox itself, otherwise it cannot work.

I've updated the [README](https://github.com/pyrho/alfred-firefoxtabswitch/blob/master/README.md) with some troubleshooting steps, you could try that and report back here.

**Comment by jknight** [comment]
Thanks for the troubleshooting steps !  It took some steps but I got it working !

1) change node version (npm install with node v14.3.0)
2) restart Firefox a couple times
3) possibly a few other steps

:)

<img width="587" alt="image" src="https://user-images.githubusercontent.com/84268/84833204-ab746800-b026-11ea-89ad-e36b8b42f823.png">
