### ISSUE TITLE
[Feature Request] Show tabs by most recently used order

### ISSUE THREAD

**Issue by sinewave** [pyrho/alfred-firefoxtabswitch#5]
One feature request, that I've always longed for but seems has never been possible without a complimentary firefox addon, is the ability for the default sorting of the tabs to be by most recently used e.g. typing "fw" would list all tabs by most recently used.

I'm constantly jumping in and out of my browser all day and often times have a lot of tabs open and don't often remember the name of the tab so having a shortcut that quickly opens up my ff tabs sorted by MRU would be A M A Z I N G!!!

Thx

**Comment by pyrho** [comment]
Hey there,

That's actually a great idea !
To be honest (and I should update the readme in accordance), I'm currently using the wonderful [alfred-firefox](https://github.com/deanishe/alfred-firefox/) which has is a superset of this plugin.

There is actually a [PR opened](https://github.com/deanishe/alfred-firefox/issues/12) over there for exactly this.
Maybe my time would be better spent implementing it there.

**Comment by sinewave** [comment]
WOW... A M A Z I N G!!!

Can't wait to try this out... hopefully he merges your PR soon. Tku!

**Comment by sinewave** [comment]
Not to be ungrateful, but another idea that I think could really improve this/alfred-firefox which is to use the site favicon for the image in Alfred. 

Not sure if this is possible, or even something you think would be interesting, but I personally feel like it would be great to quickly find the tab/bookmark you're looking for. Would also look a lot cooler.

Another poor mans solution would be to allow users to use their own icons e.g. you could store them in a folder in the workflow with a pre-defined location and naming convention that the workflow could use or otherwise fall back to the default icon. I'm a creature of habit so ~10-20 icons would cover most sites/bookmarks I visit on a daily basis 😄

**Comment by pyrho** [comment]
> Would also look a lot cooler.

Agreed, you can open a feature request over [there](https://github.com/deanishe/alfred-firefox/); I would use it (but I ain't got time to code it ^^).

**Comment by sinewave** [comment]
Sounds good, thx again for adding this PR!!!
